name: Bug Report
description: Create a bug report
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: reproduce-bug
    attributes:
      label: Reproducing the bug
      description: |
        Clear, formated, and easy to follow steps to reproduce the behavior:
      placeholder: e.g.: You can reproduce this issue by running the quickstart and doing `curl ...`
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant configuratino
      description: Please copy and paste any relevant configuration. This will be automatically formatted into code, so no need for backticks.
      render: yml
  - type: text
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - FreeBSD
        - Other
  - type: dropdown
    id: deployment
    attributes:
      label: Where are you deploying?
      options:
        - Docker
        - Docker Compose
        - Kubernetes with Helm
        - Kubernetes
        - Other
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
